MODEL:
  TYPE: generalized_rcnn
  #CONV_BODY: ResNet.ResNet50_conv4_body
  CONV_BODY: VGG16.VGG16_conv5_body
  FASTER_RCNN: false
NUM_GPUS: 4
DEDUP_BOXES:  0.125
RESNETS:
  #IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/vgg16_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  #BASE_LR: 0.0002
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 80000
  #STEPS: [0, 12000, 16000]
  STEPS: [0, 40000]
FAST_RCNN:
  #ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  #ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  #ROI_BOX_HEAD: oicr_heads.roi_2mlp_head
  ROI_BOX_HEAD: VGG16.VGG_roi_fc_head
  ROI_XFORM_METHOD: RoIPoolF
TRAIN:
  SCALES: (480, 576, 688, 864, 1200)
  #SCALES: (600, )
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  #PROPOSAL_FILES: ('data/selective_search_data/voc_2007_train.pkl', 'data/selective_search_data/voc_2007_val.pkl', 'data/selective_search_data/voc_2012_train.pkl', 'data/selective_search_data/voc_2012_val.pkl',)
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_train.pkl', 'data/selective_search_data/voc_2007_val.pkl')
TEST:
  SCALE: 688
  #SCALE: 480
  MAX_SIZE: 2000
  NMS: 0.3
  #RPN_PRE_NMS_TOP_N: 6000
  #RPN_POST_NMS_TOP_N: 1000
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_test.pkl',)
  BBOX_REG: true
  #BBOX_AUG:
  #  ENABLED: true
  #  H_FLIP: true
  #  SCALES: (480, 576, 864, 1200)
  #  SCALE_H_FLIP: true
  #  MAX_SIZE: 2000
  #  SCORE_HEUR: AVG
  #  COORD_HEUR: AVG
