MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: false
NUM_GPUS: 4
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 36000
  STEPS: [0, 24000, 32000]
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (600,)
  MAX_SIZE: 1000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_train.pkl', 'data/selective_search_data/voc_2007_val.pkl', 'data/selective_search_data/voc_2012_train.pkl', 'data/selective_search_data/voc_2012_val.pkl',)
  #PROPOSAL_FILES: ('data/selective_search_data/voc_2007_train.pkl', )
TEST:
  SCALE: 600
  MAX_SIZE: 1000
  NMS: 0.5
  #RPN_PRE_NMS_TOP_N: 6000
  #RPN_POST_NMS_TOP_N: 1000
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_test.pkl',)
