MODEL:
  TYPE: wsddn
  CONV_BODY: VGG16.VGG16_conv5_body
  FASTER_RCNN: false
NUM_GPUS: 1
DEDUP_BOXES:  0.125
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/vgg16_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  #BASE_LR: 0.0002
  BASE_LR: 0.0002
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 80000
  STEPS: [0, 40000]
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.VGG_roi_fc_head
  ROI_XFORM_METHOD: RoIPoolF
TRAIN:
  SCALES: (480, 576, 688, 864, 1200)
  #SCALES: (688, )
  MAX_SIZE: 2000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 512
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_train.pkl', 'data/selective_search_data/voc_2007_val.pkl')
TEST:
  SCALE: 688
  MAX_SIZE: 2000
  NMS: 0.3
  PROPOSAL_FILES: ('data/selective_search_data/voc_2007_test.pkl',)
  BBOX_REG: false
  #BBOX_AUG:
  #  ENABLED: true
  #  H_FLIP: true
  #  SCALES: (480, 576, 864, 1200)
  #  SCALE_H_FLIP: true
  #  MAX_SIZE: 2000
  #  SCORE_HEUR: AVG
  #  COORD_HEUR: AVG
